version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - ChristophShyper
    groups:
      gha-all:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    assignees:
      - ChristophShyper
    groups:
      docker-base-images:
        patterns:
          - "*"
