name: (Auto) Create Pull Request

on:
  push:
    branches-ignore:
      - master
      - dependabot/**

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          version: 3.x

      - name: Run linters
        run: task lint

  build-and-push:
    name: Build and push
    runs-on: ubuntu-24.04-arm
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          version: 3.x

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Get Docker commands
        run: task docker:cmds

      - name: Build and push test image
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: task docker:push

      - name: Inspect image
        run: task docker:push:inspect

  pull-request:
    name: Pull Request
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          version: 3.x

      - name: Get template
        run: task git:get-pr-template

      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignee: ${{ github.actor }}
          template: .tmp/PULL_REQUEST_TEMPLATE.md
          get_diff: true
