name: (Auto) Pull Request Create

on:
  push:
    branches-ignore:
      - master
      - main
      - dependabot/**

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  call:
    uses: devops-infra/.github/.github/workflows/reusable-auto-pull-request-create.yml@v1
    with:
      profile: actions
    secrets: inherit
