name: (Automatic) Release Create

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  call:
    uses: devops-infra/.github/.github/workflows/reusable-automatic-release-create.yml@v1
    with:
      profile: actions
    secrets: inherit
