name: (Cron) Check dependencies

on:
  schedule:
    - cron: 0 5 * * 1
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: read

jobs:
  call:
    uses: devops-infra/.github/.github/workflows/reusable-cron-check-dependencies.yml@v1
    with:
      profile: actions
    secrets: inherit
