name: Weekly Dependency Check

on:
  schedule:
    # Run every Monday at 08:00 UTC
    - cron: 0 8 * * 1

permissions:
  contents: read
  packages: write

jobs:
  dependency-check:
    name: Test Dependencies
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Task
        uses: arduino/setup-task@v2.0.0
        with:
          version: 3.x

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Install QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: amd64,arm64

      - name: Get Docker commands
        run: task docker:cmds

      - name: Build and push test image
        run: task docker:push

      - name: Inspect image
        run: task docker:push:inspect
